name: Testing the JavaScript code style

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install --only=dev
    - name: Run eslint
      run: |
        npx eslint --color .